# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('credit_card', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, help_text='User wishes', null=True)),
                ('locator', models.CharField(help_text='Booking locator', max_length=250)),
                ('price', models.FloatField(help_text='Total booking price')),
                ('amount_people', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('family', 'Family'), ('suite', 'Suite')], default='standard', max_length=5)),
                ('price', models.FloatField(help_text='Price per night')),
                ('max_people_allowed', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room-images')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_booking.Room'),
        ),
    ]
