# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(help_text='Price per night in Euros'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('family', 'Family'), ('suite', 'Suite')], default='standard', max_length=8),
        ),
    ]
