# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0002_auto_20180107_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='locator',
            field=models.CharField(blank=True, help_text='Booking locator', max_length=250),
        ),
    ]
