# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0004_auto_20180107_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room-images/'),
        ),
    ]
