# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0005_auto_20180107_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount_people',
            field=models.IntegerField(default=1),
        ),
    ]
